spring:
  application:
    name: homepage-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false                        # 表示是否从 Eureka Server 中获取注册信息，默认为 true
    register-with-eureka: false                  # 表示是否将自己注册到 Eureka Server 默认为 true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
